# Generated by Django 4.0.5 on 2023-07-11 03:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the prompt.', max_length=80, verbose_name='Title')),
                ('cover', models.ImageField(help_text='A cover image for the prompt.', upload_to='covers/', verbose_name='Cover image')),
                ('description', models.CharField(help_text='Describe what your prompt does to a potential buyer. A more detailed description will increase your sales.', max_length=500, verbose_name='Description')),
                ('style', models.CharField(choices=[('creative', 'More Creative'), ('balanced', 'More Balanced'), ('precise', 'More Precise')], default='creative', help_text='Choose a conversation style for your prompt.', max_length=8, verbose_name='Conversation style')),
                ('content', models.TextField(help_text='Write the content of your prompt.', verbose_name='Content')),
                ('output', mdeditor.fields.MDTextField(help_text='Example output of your prompt.', verbose_name='Example output')),
                ('price_dollar', models.DecimalField(decimal_places=2, help_text='Set the price of your prompt in US dollars.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price (US Dollar)')),
                ('price_yuan', models.DecimalField(decimal_places=2, help_text='Set the price of your prompt in Chinese yuan.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price (Chinese Yuan)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the prompt was uploaded.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the prompt was last updated.', verbose_name='Ppdated at')),
                ('feedback', mdeditor.fields.MDTextField(blank=True, help_text='Feedbacks to the seller of the prompt.', null=True, verbose_name='Feedback')),
                ('approved', models.BooleanField(default=False, help_text='Whether the prompt is approved by an admin or not.', verbose_name='Approved')),
                ('category', models.ManyToManyField(help_text='Categories of the prompt.', related_name='prompt', to='prompts.category', verbose_name='Category')),
                ('seller', models.ForeignKey(help_text='The user who created and sells the prompt.', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PromptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Prompt type',
                'verbose_name_plural': 'Prompt types',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('unionpay', 'UnionPay'), ('wechatpay', 'WeChatPay')], max_length=10, verbose_name='payment method')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='prompts.prompt')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='types',
            field=models.ManyToManyField(help_text='Choose one or more types for your prompt.', to='prompts.prompttype', verbose_name='Prompt types'),
        ),
    ]
