# Generated by Django 4.0.5 on 2023-07-09 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether the prompt is approved by an admin or not.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.ManyToManyField(help_text='Categories of the prompt.', related_name='prompt', to='prompts.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='content',
            field=models.TextField(help_text='Write the content of your prompt.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='cover',
            field=models.ImageField(help_text='A cover image for the prompt.', upload_to='covers/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the prompt was uploaded.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='description',
            field=models.CharField(help_text='Describe what your prompt does to a potential buyer. A more detailed description will increase your sales.', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedbacks to the seller of the prompt.', null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='price_dollar',
            field=models.DecimalField(decimal_places=2, help_text='Set the price of your prompt in US dollars.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price (US Dollar)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='price_yuan',
            field=models.DecimalField(decimal_places=2, help_text='Set the price of your prompt in Chinese yuan.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price (Chinese Yuan)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='seller',
            field=models.ForeignKey(help_text='The user who created and sells the prompt.', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='style',
            field=models.CharField(choices=[('creative', 'More Creative'), ('balanced', 'More Balanced'), ('precise', 'More Precise')], default='creative', help_text='Choose a conversation style for your prompt.', max_length=8, verbose_name='Conversation style'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(help_text='The title of the prompt.', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='types',
            field=models.ManyToManyField(help_text='Choose one or more types for your prompt.', to='prompts.prompttype', verbose_name='Prompt types'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the prompt was last updated.', verbose_name='Ppdated at'),
        ),
    ]
